import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

import {
  faSearch,
  faHeart,
  faStar,
  faPlus,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faChevronUp,
  faFilterCircleXmark,
  faRankingStar,
  faGamepad,
  faXmark,
  faCalendarDay,
  faCrosshairs,
  faFilter,
  faListCheck,
  faList,
  faRocket,
  faArrowLeftLong,
  faArrowRightLong,
  faArrowLeft,
  faArrowRight,
  faComment,
  faComments,
  faRobot,
  faWandMagicSparkles,
  faPaperPlane,
  faUser,
  faUserPlus,
  faUsers,
  faSignal,
  faThumbsUp,
  faThumbsDown,
  faPlay,
  faBell,
  faRightFromBracket,
  faTrash,
  faCheck,
  faCog,
  faSpinner,
  faClock,
  faPen,
  faTriangleExclamation,
  faArrowUpRightFromSquare,
  faCalendar,
  faIdCard,
} from "@fortawesome/free-solid-svg-icons";

import {
  faWindows,
  faPlaystation,
  faXbox,
  faSteam,
} from "@fortawesome/free-brands-svg-icons";

export default defineNuxtPlugin((nuxtApp) => {
  library.add(
    faSearch,
    faHeart,
    faStar,
    faPlus,
    faChevronLeft,
    faChevronRight,
    faChevronDown,
    faChevronUp,
    faFilterCircleXmark,
    faRankingStar,
    faWindows,
    faPlaystation,
    faXbox,
    faSteam,
    faGamepad,
    faXmark,
    faCalendarDay,
    faCrosshairs,
    faFilter,
    faListCheck,
    faList,
    faRocket,
    faArrowLeftLong,
    faArrowRightLong,
    faArrowLeft,
    faArrowRight,
    faComment,
    faComments,
    faRobot,
    faWandMagicSparkles,
    faPaperPlane,
    faUser,
    faUserPlus,
    faUsers,
    faSignal,
    faThumbsUp,
    faThumbsDown,
    faPlay,
    faBell,
    faRightFromBracket,
    faTrash,
    faCheck,
    faCog,
    faSpinner,
    faClock,
    faPen,
    faTriangleExclamation,
    faArrowUpRightFromSquare,
    faCalendar,
    faIdCard,
  );

  nuxtApp.vueApp.component("FontAwesomeIcon", FontAwesomeIcon);
});
